{% set name = "privacy-meter" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Privacy-Meter-{{ version }}.tar.gz
  sha256: fe9c855b6080f2b3c2028a62ceca3700e53729734afa67c7f808f217e51928b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - scikit-learn
    - seaborn
    - setuptools
    - scipy
    - pandas
    - jinja2
    - pillow

test:
  imports:
    - privacy_meter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/privacytrustlab/ml_privacy_meter
  summary: 'Privacy Meter: An open-source library to audit data privacy in statistical and machine learning algorithms.'
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
